/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefDashboardRouteImport } from './routes/brief-dashboard'
import { Route as BriefMixedRouteImport } from './routes/brief-mixed'
import { Route as BriefWrittenRouteImport } from './routes/brief-written'
import { Route as ScreenInventoryRouteImport } from './routes/screen-inventory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefDashboardRoute = BriefDashboardRouteImport.update({
  id: '/brief-dashboard',
  path: '/brief-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefMixedRoute = BriefMixedRouteImport.update({
  id: '/brief-mixed',
  path: '/brief-mixed',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefWrittenRoute = BriefWrittenRouteImport.update({
  id: '/brief-written',
  path: '/brief-written',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenInventoryRoute = ScreenInventoryRouteImport.update({
  id: '/screen-inventory',
  path: '/screen-inventory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brief-dashboard': typeof BriefDashboardRoute
  '/brief-mixed': typeof BriefMixedRoute
  '/brief-written': typeof BriefWrittenRoute
  '/screen-inventory': typeof ScreenInventoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brief-dashboard': typeof BriefDashboardRoute
  '/brief-mixed': typeof BriefMixedRoute
  '/brief-written': typeof BriefWrittenRoute
  '/screen-inventory': typeof ScreenInventoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brief-dashboard': typeof BriefDashboardRoute
  '/brief-mixed': typeof BriefMixedRoute
  '/brief-written': typeof BriefWrittenRoute
  '/screen-inventory': typeof ScreenInventoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brief-dashboard'
    | '/brief-mixed'
    | '/brief-written'
    | '/screen-inventory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brief-dashboard'
    | '/brief-mixed'
    | '/brief-written'
    | '/screen-inventory'
  id:
    | '__root__'
    | '/'
    | '/brief-dashboard'
    | '/brief-mixed'
    | '/brief-written'
    | '/screen-inventory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefDashboardRoute: typeof BriefDashboardRoute
  BriefMixedRoute: typeof BriefMixedRoute
  BriefWrittenRoute: typeof BriefWrittenRoute
  ScreenInventoryRoute: typeof ScreenInventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief-dashboard': {
      id: '/brief-dashboard'
      path: '/brief-dashboard'
      fullPath: '/brief-dashboard'
      preLoaderRoute: typeof BriefDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief-mixed': {
      id: '/brief-mixed'
      path: '/brief-mixed'
      fullPath: '/brief-mixed'
      preLoaderRoute: typeof BriefMixedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief-written': {
      id: '/brief-written'
      path: '/brief-written'
      fullPath: '/brief-written'
      preLoaderRoute: typeof BriefWrittenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-inventory': {
      id: '/screen-inventory'
      path: '/screen-inventory'
      fullPath: '/screen-inventory'
      preLoaderRoute: typeof ScreenInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefDashboardRoute: BriefDashboardRoute,
  BriefMixedRoute: BriefMixedRoute,
  BriefWrittenRoute: BriefWrittenRoute,
  ScreenInventoryRoute: ScreenInventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
